#!/bin/zsh

# System -------------------------- System -------------------------- System #
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias cx='chmod u+x'

## clear history
alias hclear='rm $HISTFILE'

# Git ------------------------------ Git ------------------------------- Git #
## for more take a look to https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
alias gfp='git fetch --all --tags --prune --prune-tags'

# Check if git is enabled for zsh in $plugins, else use own commands
if [[ ! "$plugins" =~ "git" ]]; then
    echo "Git plugin not enabled, using custom aliases"
    alias gst='git status'
    alias ga='git add'
    alias gc='git commit --verbose'
    alias gca='git commit -a'
    alias gco='git checkout'
    alias gp='git push'
    alias ggp='git push origin'
    alias gl='git pull'
    alias ggl='git pull origin'
    alias gm='git merge'
    alias grh='git reset'
    alias grhh='git reset --hard'
    alias gr='git remote'
    alias grm="git rm"
    alias gcl='git clone --recurse-submodules'
    alias gd="git diff"
    alias gds="git diff --staged"
    alias gb='git branch'
    alias gbd='git branch -d'
    alias gf='git fetch'
    alias gfo='git fetch origin'
fi

# Composer ----------------------- Composer ----------------------- Composer #
alias c='XDEBUG_MODE=off composer'
alias composer='XDEBUG_MODE=off composer'

# Custom paths ----------------- Custom paths ----------------- Custom paths #
alias cpath='cd $vCustomPath'

# Custom commands ------------ Custom commands ------------- Custom commands #
alias openvsc='open -a "Visual Studio Code" $1' # open given file with Visual Studio Code
alias zshreload='source ~/.zshrc' # reload ZSH
alias grep='grep --color=auto' # colorize `grep` output
alias dexec='docker exec -t -i'
