#!/bin/zsh

# antigen (needed for zsh-autosuggestions and zsh-syntax-highlighting)
source /usr/local/share/antigen/antigen.zsh

# zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions
#antigen bundle zsh-users/zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238#issuecomment-389324292
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}

zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting
#antigen bundle zsh-users/zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-history-substring-search https://github.com/zsh-users/zsh-history-substring-search
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# Mapping arrow keys
bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down
