#!/bin/zsh

# Only works on .zshrc
#plugins=(git macos brew colored-man-pages colorize npm symfony2 composer docker docker-compose kubectl helm 1password)

# antigen (needed for zsh-autosuggestions and zsh-syntax-highlighting)
source $(brew --prefix)/share/antigen/antigen.zsh

# zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-history-substring-search https://github.com/zsh-users/zsh-history-substring-search
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238#issuecomment-389324292
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}

zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# Mapping arrow keys
bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down
